### ISSUE TITLE
Distinct table labels missing per current 11.x limitation

### ISSUE THREAD

**Issue by tdigangi** [terraform-google-modules/terraform-google-bigquery#11]
Current Issue: Trying to pair a table creation with "list of maps" fails when a lookup is performed on the table labels

v0.2.0 May lack support for multiple tables with distinct labels as lookups only work with flat maps and there will be more rich functionality available in tf 12 to handle this need.

**Comment by ingwarr** [comment]
@tdigangi Could you please provide me with an example or path to reproduce current behavior, it not completely clear for me

**Comment by aaron-lane** [comment]
Fixed by #20.
