### ISSUE TITLE
In what capacity are schema migrations supported, and if so, is that mentioned in the docs yet?

### ISSUE THREAD

**Issue by pofl** [terraform-google-modules/terraform-google-bigquery#113]

**Comment by morgante** [comment]
We simply pass the schema to the underlying BigQuery API, without any special support for migrations.

**Comment by pofl** [comment]
So if I change the schema of a table in the tf definition, it won't update the schema in BQ? Does it throw an error or ignore the change?

**Comment by morgante** [comment]
It will update the schema in BQ, based on these constraints: https://cloud.google.com/bigquery/docs/managing-table-schemas

**Comment by morgante** [comment]
Feel free to file an issue on the provider: https://github.com/hashicorp/terraform-provider-google
