### ISSUE TITLE
Google bigquery job Error 400: dataset Not Found

### ISSUE THREAD

**Issue by Madi200** [terraform-google-modules/terraform-google-bigquery#122]
I am trying to create a bigquery job and insert data from a sql cloud instance database table. For data ingestion, I have setup external connection with cloud SQL in GCP and can create Schedule Query using MERGE INTO(SQL query), using bigquery UI. As a result of creating this query I am able to insert data into BQ from sql instance.
For doing the same task using terraform I have setup dataset, table and external connection. But the blocker is google_bigquery_job in terraform. Even though the dataset is available in BQ, on running the script I am receiving following error:
**Error: Error creating Job: googleapi: Error 404: Not found: Dataset (Here Dataset ID), notFound**

Related Script is as follows:

` resource "google_bigquery_job" "job" {
  provider=google
  job_id     = "job_query_testing"
  labels = {
    "example-label" ="example-value"
  }

  query {
    query                           = <<EOF SQL query here EOF
      use_legacy_sql = false
     write_disposition="WRITE_APPEND"
    destination_table {
      project_id = var.project_id
      dataset_id = google_bigquery_dataset.main.dataset_id
      table_id =  google_bigquery_table.main.table_id
    }

    allow_large_results = true

    script_options {
      key_result_statement = "LAST"
    }
  }
} 
`

**Comment by morgante** [comment]
This repo is for our Terraform module, not general problems with the Terraform resource.

For issues with the `google_bigquery_job` resource, please open a provider issue: https://github.com/hashicorp/terraform-provider-google
