### ISSUE TITLE
Provider Version pinning

### ISSUE THREAD

**Issue by matty-rose** [terraform-google-modules/terraform-google-bigquery#127]
Is there any particular reason the google provider version is pinned like so `~> 3.63.0`, specifically with the trailing 0? This only allows providers of the version `3.63.x` which is very restrictive. Other modules from `terraform-google-modules` (e.g. [gke](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/versions.tf) and [pubsub](https://github.com/terraform-google-modules/terraform-google-pubsub/blob/master/versions.tf)) and  seem to pin like `~> 3.52` or `>= 3.x.0, < 4.0.0` which is more permissive for users.

Edit: this seems like something that was introduced only in release `5.1.0`

**Comment by morgante** [comment]
Yeah this was simply a mistake. We will fix it.
