### ISSUE TITLE
for_each in multiple_tables

### ISSUE THREAD

**Issue by N214** [terraform-google-modules/terraform-google-bigquery#129]
Hello, I would like to know if it is possible to include a for_each iteration within the tables section.

I am trying to create one dataset but with mutilple tables in it.  And I would like to iterate through with an for_each. 

Thanks

**Comment by morgante** [comment]
The tables variable accepts a list. You can provide multiple tables in the list.

**Comment by N214** [comment]
Yes I saw the multi table example and my objective is to not copy paste multiple tables with almost the same configuration. 
Is it possible to have one table and iterate through a list of different table names for example?

**Comment by morgante** [comment]
You can do that using standard Terraform functionality. There's nothing special about the module, you just need to learn Terraform syntax.

For example:
```
module "bigquery" {
  source  = "terraform-google-modules/bigquery/google"
  version = "~> 4.4"

  dataset_id                  = "foo"
  dataset_name                = "foo"
  description                 = "some description"
  project_id                  = "<PROJECT ID>"
  location                    = "US"
  default_table_expiration_ms = 3600000

  tables = [for name in ["one", "two"]: {
   table_id           =  name,
    schema             =  "",
    time_partitioning  = {
      type                     = "DAY",
      field                    = null,
      require_partition_filter = false,
      expiration_ms            = null,
  }]
}
``1
