### ISSUE TITLE
How does Terraform know if a table exists already?

### ISSUE THREAD

**Issue by csteez** [terraform-google-modules/terraform-google-bigquery#13]
Hi! I'm using Terraform to define a few datasets in BQ and sometimes actions other than a TF create tables. How does TF define a new table vs an existing one in the module? I don't see anything along the lines of a flag (other than creation time, which we aren't using).

**Comment by aaron-lane** [comment]
Hi @csteez!

Are you inquiring about the ability to import an existing BigQuery table to a Terraform state which uses this module?

**Comment by csteez** [comment]
I was wondering how to properly manage existing tables in BQ with TF, but I think I've got it sorted so I'll close this. 

Thanks for your speedy response!
