### ISSUE TITLE
Configure CI pipeline

### ISSUE THREAD

**Issue by aaron-lane** [terraform-google-modules/terraform-google-bigquery#14]
- [ ] define Terraform test fixture infrastructure in https://github.com/googlecloudplatform/cloud-foundation-toolkit
- [ ] define Concourse pipeline in https://github.com/googlecloudplatform/cloud-foundation-toolkit
- [ ] update `Makefile`, `test/ci_integration.sh`, and related files based on https://github.com/terraform-google-modules/terraform-google-module-template.

**Comment by kiran002** [comment]
I am interested in this, can i pick this up? also could you add more information? Thanks!

**Comment by aaron-lane** [comment]
Hi @kiran002!

Thank you for your enthusiasm. Unfortunately, this task is best suited for one of the core contributors as our CI system is not currently open to the public.

**Comment by kiran002** [comment]
Thanks for making it clear, @aaron-lane. Can you tell me how i can become a core contributor? :)

**Comment by aaron-lane** [comment]
At present, the core team is limited to Googlers and our partners. We plan on improving the CI system so that other contributors can also access it as we recognize the inaccessibility is a significant impediment to development.
