### ISSUE TITLE
Add num_rows, num_bytes and last_modified_time to bigquery table lifecycle ignore changes

### ISSUE THREAD

**Issue by dennislapchenko** [terraform-google-modules/terraform-google-bigquery#144]
### TL;DR

Every terraform plan for bigquery table has these obviously useless fields in "Objects have changed". This will always be the case and it jsut bloats plans. Perhaps we can ignore these?

### Terraform Resources

```markdown
resource "google_bigquery_table" "main" {
  lifecycle {
    ignore_changes = [
      num_rows, num_bytes, last_modified_time
    ]
  }
}
```

**Comment by morgante** [comment]
Are you actually seeing a diff on these? Please share your `terraform plan` output where you're seeing this issue.

They are computed attributes which should not cause a diff: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_table#attributes-reference

**Comment by 0fuzz** [comment]
We see the same, also etag.

Now our plan body is too big for a github comment, so also planning to add the ignore changes mentioned above. If I can fix this in any other way, please enlighten me.

> Note: Objects have changed outside of Terraform
> 
> Terraform detected the following changes made outside of Terraform since the
> last "terraform apply":
> 
>   # module.managed_client_project.module.xxx.google_bigquery_table.xxx has changed
>   ~ resource "google_bigquery_table" "xxx" {
>         id                  = "xxx"
>       ~ last_modified_time  = 1649398577299 -> 1649402175533
>       ~ num_bytes           = 23768324 -> 23811008
>       ~ num_rows            = 51110 -> 51183
>         # (14 unchanged attributes hidden)
> 
>         # (1 unchanged block hidden)
>     }
