### ISSUE TITLE
Add ability to not set expiration times

### ISSUE THREAD

**Issue by thefirstofthe300** [terraform-google-modules/terraform-google-bigquery#15]
Based on my reading of the API and the module, it is currently impossible to create a BigQuery dataset or table without setting default expiration IDs. Requiring data to expire after a certain amount of time should not be a requirement to use this module.

If we need to choose between specifying a default timeout and not, I vote not.

**Comment by morgante** [comment]
Indeed, let's look at using the new 0.12 nil to support this.

**Comment by aaron-lane** [comment]
@ingwarr let's reconsider the implementation from #21. The default should be `null`.

**Comment by ingwarr** [comment]
I' ve checked it works with `null`, it optional parameter

**Comment by aaron-lane** [comment]
Fixed by #23. Thanks @ingwarr!
