### ISSUE TITLE
Support Schema Options to allow updating columns

### ISSUE THREAD

**Issue by abhayshiravanthe** [terraform-google-modules/terraform-google-bigquery#175]
### TL;DR

Allow `schema_update_options = ["ALLOW_FIELD_ADDITION"]` to allow adding a nullable field to the schema. Column additions to existing table is not straightforward without this.

**Comment by imrannayer** [comment]
This is a parameter for `google_bigquery_job`. I cant find `google_bigquery_job` in this module or sub-module. Can you plz point to the code where this can parameter can be added?
