### ISSUE TITLE
Support BI Engine for Big Query

### ISSUE THREAD

**Issue by lucienfregosibodyguard** [terraform-google-modules/terraform-google-bigquery#177]
### TL;DR

I would like to set up BI engine through terraform https://console.cloud.google.com/bigquery/admin/bi-engine

### Terraform Resources

```markdown
google_bigquery.bi_engine
```

**Comment by imrannayer** [comment]
Is there a terraform support for this feature? If not then you can open a new feature request on provider site. 

https://github.com/hashicorp/terraform-provider-google/issues
