### ISSUE TITLE
Support BigQuery clustering in terraform

### ISSUE THREAD

**Issue by ashuclh** [terraform-google-modules/terraform-google-bigquery#26]
Hi,

It would be great if we could create BigQuery tables with setting clustering columns.
Documentation: https://cloud.google.com/bigquery/docs/creating-clustered-tables

Affected Resource(s)
google_bigquery_table

**Comment by morgante** [comment]
Is this supported on the bigquery resource already?

**Comment by ashuclh** [comment]
yes

**Comment by morgante** [comment]
Can you share which attribute you're looking to leverage? From here: https://www.terraform.io/docs/providers/google/r/bigquery_table.html

**Comment by ashuclh** [comment]
the mentioned attribute is not listed in this page.In bigquery we can created clustered partition in a table where it displays as "Clustered by" if we click on Details tab

**Comment by tdigangi** [comment]
- The current module functionality is allowing users to create a dataset + tables within the supported attributes of Terraform.
- Terraform does not currently support this functionality. I have created Terraform [Issue 22446](https://github.com/hashicorp/terraform/issues/22446) to add this to their backlog.

**Comment by averbuks** [comment]
Thank you @ashuclh for raising that, `clustering` available for gcp-provider starting from version 2.14 https://github.com/terraform-providers/terraform-provider-google/blob/master/CHANGELOG.md#2140-august-28-2019
We are going to add support soon.

**Comment by averbuks** [comment]
Done by #40

**Comment by milesmatthias** [comment]
@averbuks @morgante `clustering` support was actually only added to the TF Google provider in 3.0.0, so adding clustering and re-releasing this module with that supported means this module cannot be used with the TF Google provider 2.X.

**Comment by morgante** [comment]
@averbuks Let's update the minimum version to 3.0.0.
