### ISSUE TITLE
Allow creation of UDFs in a dataset

### ISSUE THREAD

**Issue by chetaldrich** [terraform-google-modules/terraform-google-bigquery#32]
So I was looking for something that might allow me to define a UDF inside a Google Cloud BigQuery dataset, and wasn't able to find anything here. It seems like the Go client library allows for creation of these by creation of a Routine, defined [here](https://godoc.org/cloud.google.com/go/bigquery#Routine). 

It might be worthwhile to consider adding this functionality to the module, considering they can now be defined in a persistent manner (see [this](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_function_statement))

**Comment by morgante** [comment]
Thanks for the request, we are looking at this. Would you mind providing an example of how you'd like to invoke this in the module?

**Comment by chetaldrich** [comment]
I'm currently imagining something like this. In this example I would ideally have defined a function with two arguments of type FLOAT64 and an output of FLOAT64 in some dataset called `fn`: 

```
resource "google_bigquery_dataset" "fn" {
  dataset_id = "fn"
  location = "US"
  project = google_project.project_here.project_id
}

data "udf_parameters" "udf_args" {
  named_parameter {
    param_name = "my_arg1"
    param_type = "FLOAT64"
  }

  named_parameter {
    param_name = "my_arg2"
    param_type = "FLOAT64"
  }
}

resource "google_bigquery_udf" "my_udf" {
  project = google_project.project_here.project_id
  dataset_id = google_bigquery_dataset.fn.dataset_id
  persistent_function_id = "MY_UDF"
  language = "js"
  arguments = data.udf_parameters.udf_args
  returns = "FLOAT64"
  body = <<EOF
  function body here, or import a file
EOF
}
```

I'm not confident this covers all the potential knobs that you can turn, but I think it covers the one mentioned [here](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_function_statement). It also seems, given a cursory reading of the golang documentation, that they can be created and removed with the parameters in this hypothetical Terraform resource.

**Comment by morgante** [comment]
Thanks for providing the example!

Just to confirm, are you using (or interested in using) this [module](https://github.com/terraform-google-modules/terraform-google-bigquery)? If you're looking to have direct resources added on the provider itself, you should open an issue [upstream](https://github.com/terraform-providers/terraform-provider-google/issues).

**Comment by chetaldrich** [comment]
It seems like this likely would need to get added to the provider, not this module. My bad. I wasn't able to find a similar issue upstream, so I'll create a new one there.

**Comment by morgante** [comment]
For what it's worth, we are planning to add this to the module as well (possibly prior to the provider).

**Comment by chetaldrich** [comment]
https://github.com/terraform-providers/terraform-provider-google/issues/4493 

I went ahead and created this upstream. I haven't used this module before (just realized this wasn't part of the core that creates resources when I first submitted this issue), but might if it is possible to add something like this to it independent of the provider. Whatever gets me the functionality to define these in a way where I don't need to write an ad-hoc script to manage them would be great. 

If there's potentially work underway to add this here, feel free to reopen, otherwise we can leave this closed.
