### ISSUE TITLE
Confused about which terraform approach to use?

### ISSUE THREAD

**Issue by bigbitbus** [terraform-google-modules/terraform-google-bigquery#36]
Hi,

I am new to BQ w/terraform.

I was planning on following this Hashicorp document to use terraform with BQ:

https://www.terraform.io/docs/providers/google/r/bigquery_table.html

But I came across this module.

Can someone comment on what direction a new project should take in this regard? The provider in Hashicorp documentation, or this module? Which may have better long term supportability?

**Comment by morgante** [comment]
The module simply wraps the resource you linked.

You can use either. The module simplifies some functionality and makes creating multiple table simpler, while directly using the resource gives you more control/flexibility.

**Comment by bigbitbus** [comment]
Thanks for the prompt response. I will go with the Hashicorp-blessed approach since I only need to create a simple setup.

IMHO the differences between the provider approach and these modules should be clarified in the documentation for these separate modules so people can make a data-driven choice.
