### ISSUE TITLE
Improve examples

### ISSUE THREAD

**Issue by morgante** [terraform-google-modules/terraform-google-bigquery#5]
Make them actually demonstrate module usage.

Notes: https://github.com/terraform-google-modules/terraform-google-bigquery/pull/3#pullrequestreview-204479815

**Comment by tdigangi** [comment]
Can we please close this issue per [pr9](https://github.com/terraform-google-modules/terraform-google-bigquery/pull/9)?

**Comment by aaron-lane** [comment]
Fixed by #9.
