### ISSUE TITLE
Add HCLS members as co-owner of bigquery module + make new release

### ISSUE THREAD

**Issue by umairidris** [terraform-google-modules/terraform-google-bigquery#53]
BigQuery is one of the major products that healthcare customers come to GCP for. Having a clean, reliable and secure module is very important from our perspective.

With the many changes I recently proposed I hope we can get them merged in and make a major release which we can use with customers going forward. Given there might be some maintenance overhead from this change and potential future changes I am happy to co-own this module representing HCLS.

**Comment by morgante** [comment]
Sure, we could definitely use the help!

To formalize this, could you add a [CODEOWNERS file](https://github.com/terraform-google-modules/terraform-google-network/blob/master/CODEOWNERS) including your name?
