### ISSUE TITLE
Update access variable to support "view" block

### ISSUE THREAD

**Issue by burnzy** [terraform-google-modules/terraform-google-bigquery#58]
Hello @morgante 

Wondering if there are plans to support the "view" block in the v4.0.0 access variable?
Currently only part of the access block is used: https://github.com/terraform-google-modules/terraform-google-bigquery/blob/master/main.tf#L31-L41

I'm referring to this view block here on the dataset resource: https://www.terraform.io/docs/providers/google/r/bigquery_dataset.html#view

This would be great as it would allow us to create authorized views easily.

**Comment by morgante** [comment]
This is now supported through the authorization submodule: https://github.com/terraform-google-modules/terraform-google-bigquery/tree/master/modules/authorization
