### ISSUE TITLE
Support for other bigquery primitives

### ISSUE THREAD

**Issue by Mark-McCracken** [terraform-google-modules/terraform-google-bigquery#59]
Hey, 

I like the library, this could potentially replace a custom liquibase change management system I was previously using with bigquery.

I was wondering if there are any plans to support other bigquery primitives, such as views, functions, or procedures? I couldn't find anything in previous issues

Thanks

**Comment by morgante** [comment]
Views are now supported.

Some preset functions are available through this submodule: https://github.com/terraform-google-modules/terraform-google-bigquery/tree/master/modules/udf

What did you have in mind for specific additions?
