### ISSUE TITLE
change tests to native inspec resources

### ISSUE THREAD

**Issue by tdigangi** [terraform-google-modules/terraform-google-bigquery#7]
Implement the following native kitchen inspec resources into the test suite.
[google_bigquery_table](https://www.inspec.io/docs/reference/resources/google_bigquery_table/)
[google_bigquery_dataset](https://www.inspec.io/docs/reference/resources/google_bigquery_dataset/)

**Comment by tdigangi** [comment]
Can we please close this issue per [pr9](https://github.com/terraform-google-modules/terraform-google-bigquery/pull/9)?

**Comment by aaron-lane** [comment]
Fixed by #9.
