### ISSUE TITLE
update/validate google provider 2.0.0

### ISSUE THREAD

**Issue by tdigangi** [terraform-google-modules/terraform-google-bigquery#8]
To help users leveraging beta and google provider ~2.0.0 the module and examples should be modified to accommodate for this  [Upgrade](https://www.terraform.io/docs/providers/google/version_2_upgrade.html) process

**Comment by tdigangi** [comment]
Can we please close this issue per [pr9](https://github.com/terraform-google-modules/terraform-google-bigquery/pull/9)?

**Comment by aaron-lane** [comment]
Fixed by #9.
