### ISSUE TITLE
Error: BigQuery service account does not exist when using CMEKs on a dataset

### ISSUE THREAD

**Issue by jlockyerstevens** [terraform-google-modules/terraform-google-bigquery#80]
Hi there

I am using the provider to:
1. Create a KMS keyring
1. Create a KMS cryptokey on that keyring
1. Grant the BigQuery service account the Encryptor/Decryptor role over that cryptokey
1. Create a BigQuery dataset with the encryption configuration to use the cryptokey.

I followed [this documentation](https://cloud.google.com/bigquery/docs/customer-managed-encryption).

The final step fails with this error:
```
Error applying IAM policy for KMS CryptoKey "projects/[PROJECT_ID]/locations/europe/keyRings/[KEYRING_NAME]/cryptoKeys/[CRYPTOKEY_NAME]": Error setting IAM policy for KMS CryptoKey "projects/[PROJECT_ID]/locations/europe/keyRings/[KEYRING_NAME]/cryptoKeys/[CRYPTOKEY_NAME]": googleapi: Error 400: Service account bq-[PROJECT_NUMBER]@bigquery-encryption.iam.gserviceaccount.com does not exist., badRequest
```

The issue also arises if I try to grant the Encryptor/Decryptor role in the IAM pane through the GCP Console GUI.
Strangely, the issue is not permanent - it seems to resolve within approximately 24 hours. All of a sudden, the service account exists and is available for granting IAM roles. Granting the required role either through the Console or by re-queueing the Terraform Plan and Apply is successful.

I can't see any pattern regarding what resolves the issue. Initially, we suspected that the account may auto-create after a first dataset is created. So we now have a pre-step that makes a dummy dataset, waits 30 mins and then completes the steps above. This still fails.

Code below:
```
// Get the project number for the environment.
data "google_project" "project_number" {}


// Create a dummy dataset to prime the BigQuery service account. NOTE: This dataset is not actually to be used.

resource "google_bigquery_dataset" "dataset_dummy" {
  dataset_id                  = "${var.environment_name}_dataset_dummy"
  location                    = var.bigquery_dataset_location
  default_table_expiration_ms = var.bigquery_dataset_default_table_expiration_ms
  description                 = "DO NOT USE THIS DATASET. Do not store any data here. It is created simply to prime the BigQuery service account."
}


// Sleep after creating the dataset. This allows the BigQuery service account to be created, enabling the use of CMEKs.

resource "time_sleep" "bigquery_wait" {
  depends_on = [google_bigquery_dataset.dataset_dummy]

  create_duration = "30m"
}


// Bind the BigQuery service account to the BigQuery CMEK, once the delay has finished.

resource "google_kms_crypto_key_iam_binding" "bigquery_dataset_cmek_iam" {
  crypto_key_id = var.bigquery_dataset_cmek_id
  role          = "roles/cloudkms.cryptoKeyEncrypterDecrypter"

  members = [
              "serviceAccount:bq-${data.google_project.project_number.number}@bigquery-encryption.iam.gserviceaccount.com",
            ]

  depends_on = [time_sleep.bigquery_wait]
}


// Sleep again after conducting the IAM binding, giving time for it to propagate.

resource "time_sleep" "bigquery_cmek_iam_wait" {
  depends_on = [google_kms_crypto_key_iam_binding.bigquery_dataset_cmek_iam]

  create_duration = "5m"
}


// Create a default dataset to house all tables in this project.

resource "google_bigquery_dataset" "dataset_1" {
  dataset_id                  = "${var.environment_name}_dataset_1"
  location                    = var.bigquery_dataset_location
  default_table_expiration_ms = var.bigquery_dataset_default_table_expiration_ms


  // Encrypt the dataset with a CMEK. (https://cloud.google.com/bigquery/docs/customer-managed-encryption)

  default_encryption_configuration {
    kms_key_name = var.bigquery_dataset_cmek_id
  }

  // Wait for the CMEK IAM binding to propagate.
  depends_on = [time_sleep.bigquery_cmek_iam_wait]
}
```

*Environment details:*
* Remote execution on Terraform Enterprise private v202004-3
* Terraform version 0.12.24
* Latest provider version
* Using a project created several weeks ago, but never actually used.

Please help! We need to understand the logic behind what spawns the BigQuery service account, so that we can add appropriate waits/retries into our build specification.
Thank you :)

**Comment by morgante** [comment]
This issue is not related to this module (it looks like you're not using the module at all in fact).

I'd recommend opening a support case with Google to ask when that service account will appear. It's probably not related to Terraform.

**Comment by prodriguezdefino** [comment]
Just for posterity, when using the recommendation stated [here](https://www.terraform.io/docs/providers/google/d/google_bigquery_default_service_account.html) the service account surfaces with the correct permissions to perform the resource creation, bear in mind the need of an explicit dependency on the IAM membership resource permissions being set on the BQ dataset resources.

**Comment by morgante** [comment]
Thanks for explaining more.

We could probably fold that into this module.

**Comment by aarosil** [comment]
The above wait delay works, the service account creation can also be triggered manually with the `bq` command (looks like those commands are also being migrated to `gcloud` currently) 

For those who find the issue in the future from a web search, this is the `bq` command to [trigger service account creation](https://cloud.google.com/bigquery/docs/customer-managed-encryption#trigger_creation_of_your_service_account )
