### ISSUE TITLE
Treat column mode = NULLABLE and unspecified column mode as the same

### ISSUE THREAD

**Issue by jasonmcboyd** [terraform-google-modules/terraform-google-bigquery#81]
I'm not sure if this is a bug report or a feature request.

If a table is created with a column that has the mode left unspecified and then later the mode is changed to "NULLABLE" `terraform plan` will indicate an update is required:

```
 ​~ schema              = jsonencode(
	 ​~ [
		 ​~ {
			 ​+ mode = "NULLABLE"
			   ​name = "AccountID"
			   ​type = "NUMERIC"
		   ​},
		 ​  <ommitted for brevity>
	   ​]
   ​)
```

Upon running `terraform apply`  Terraform will indicate that the "modification was completed successfully" when no change was actually made. Running `terraform plan` again will result in the same plan as before. The converse is also true, if the mode is initially "NULLABLE" and then later changed to unspecified the provider will indicate that the mode is going to be removed.

I understand why no change is made but I think, given that [mode defaults to "NULLABLE" when no mode is specified](https://cloud.google.com/bigquery/docs/schemas#modes), the provider should treat these as the same and not indicate that an update is required.

**Comment by morgante** [comment]
Please open an issue on the provider: https://github.com/terraform-providers/terraform-provider-google/issues
