### ISSUE TITLE
Support Table Schema to be optional

### ISSUE THREAD

**Issue by ajr80231** [terraform-google-modules/terraform-google-bigquery#82]
Currently terraform module requires schema to be defined for table creation. According to [1] and the tf native resource [2] , a schema can be optional. What should occur is:

`Schema [Optional]` The schema for the data. Schema is required for CSV and JSON formats if autodetect is not on. Schema is disallowed for Google Cloud Bigtable, Cloud Datastore backups, Avro, ORC and Parquet formats.

**Ask:** Allow schema to be optional and support the ability to enable autodetect. 

[1] https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#TableSchema

[2] https://www.terraform.io/docs/providers/google/r/bigquery_table.html

**Comment by bharathkkb** [comment]
@morgante @umairidris  does this seem reasonable to default to null if schema path is an empty string?  Currently this throws an error as we have wrapped it in a file function.
https://github.com/terraform-google-modules/terraform-google-bigquery/blob/4bd5f82da82d9c4063a60e9564a87737d9e914ec/main.tf#L60

**Comment by morgante** [comment]
Hmm, I'm not sure if we should do this in the core module. Schema-less focuses on external data sources which we don't support already and are semantically and syntactically quite different from normal BigQuery tables.

I think we might want to either (a) leave this off entirely, (b) add a separate `external_tables` variable, (c) add an external submodule.

**Comment by RNHTTR** [comment]
Any update on this? Would love to include external tables in this module
