### ISSUE TITLE
Support for Materialize views

### ISSUE THREAD

**Issue by Ja50nRu550** [terraform-google-modules/terraform-google-bigquery#83]
Google supports materialized views in BigQuery and we'd like to be able to define them via terraform.

https://cloud.google.com/bigquery/docs/materialized-views-intro

From what we can tell, the existing table/view resources do not support them yet.

**Comment by morgante** [comment]
You'll need to request this on the provider: https://github.com/terraform-providers/terraform-provider-google/issues
