### ISSUE TITLE
Schema update for bigquery table

### ISSUE THREAD

**Issue by alexandre-cruel** [terraform-google-modules/terraform-google-bigquery#87]
I'd like to create bigquery tables via terraform. 
The tables I plan to create are partitionned tables (i.e. requires a schema by default). 
This schema will potentially change in the future if I need to add some columns to my table. 
The data stored in the table isnt easy to reload.
Though it looks like updating the schema will completely recreate the table as mentionned [here](https://www.terraform.io/docs/providers/google/r/bigquery_table.html#schema-1).

So does this "any changes on the configured value will force the table to be recreated." mean I wont be able to update the schema of the table on the fly while the data isnt dropped? 
Thank you for the help and clarification

**Comment by morgante** [comment]
Unfortunately I don't think it's possible to update the schema without recreating an issue. Please file an issue here if you want that changed: https://github.com/terraform-providers/terraform-provider-google/issues
