### ISSUE TITLE
UDF module is Hard Coded and definitions duplicated

### ISSUE THREAD

**Issue by jaketf** [terraform-google-modules/terraform-google-bigquery#97]
The [UDF module](https://github.com/terraform-google-modules/terraform-google-bigquery/blob/master/modules/udf/main.tf) in this repo hard codes some specific persistent UDFs that one particular customer cared about. I don't think CFT modules is the right place for us to distribute UDFs as all of these (except check protocol) have already been donated to https://github.com/GoogleCloudPlatform/bigquery-utils/tree/master/udfs/community.

I'm not sure why the source for the UDFs is also duplicated in a [bash script](https://github.com/terraform-google-modules/terraform-google-bigquery/blob/master/modules/udf/scripts/persistent_udfs.sh) (which appears unused)

cc: @bharathkkb @umairidris @milesmatthias

IHAC that would be keen to consume a general BigQuery UDF module rather than one that hard codes these particular UDFs.
Would it be ok if I open a PR that overwrites this module? we can take the existing UDF definitions and throw them in an example for this submodule.

@WillBeebe can you please ask our favorite ad exchange if they depend on this UDF submodule directly from this OSS repo and help them migrate if so?

**Comment by bharathkkb** [comment]
@jaketf looks like we switched from shell script to gcloud module midway in https://github.com/terraform-google-modules/terraform-google-bigquery/pull/37 but forgot cleanup the script. I am not well versed IRL use-cases for this module but there maybe a value add in providing a default set of UDFs. 

Perhaps the interface could be such that if no custom udfs are provided we use current set (this would also prevent a breaking change).

**Comment by jaketf** [comment]
I think IRL there is exactly one user of this module and they only use a modified version in an "fork".
IMO, the existing set is useless as all users should migrate to using the bigquery utils maintained versions of these UDFs or their own source SQL. We notably don't test these UDF definitions in this repo so I'm not keen to bring these forward.

**Comment by morgante** [comment]
I agree that maintaining a copy of the UDFs here doesn't make much sense.

If we wanted to allow incorporation of community UDFs it would better to facilitate import from https://github.com/GoogleCloudPlatform/bigquery-utils/tree/master/udfs/community but that seems unnecessary at this juncture.
